name: publican
version: 0.1.4
description: The package that will help you out with Dart's Pub
author: Leo Cavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/publican

dependencies:
  args: ^1.4.1
  http: ^0.11.3+16

dev_dependencies:
  yaml: ^2.1.13
  test: ^1.3.2

executables:
  publican:

environment:
  sdk: '>=2.0.0 <3.0.0'
